### PR TITLE
Swap with drop-in API replacement working on Windows as well

### PR DESCRIPTION
**Pull request by vnlitvinov**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Replace `blessings` with `blessed` which is an API-compatible fork that works on Windows as well as on other platforms.
Upstream `gpustat` has already moved to it but has not made a release yet.

### CODE REVIEW

**Comment by vnlitvinov** [comment]
I was too hasty on pushing "create" button, need to prepare some source patches. Converting to draft...

**Comment by vnlitvinov** [comment]
@conda-forge-admin please rerender

**Comment by vnlitvinov** [comment]
@conda-forge/gpustat this is ready for review

**Comment by hadim** [comment]
There are some important modifications made here that does not really reflect the current version of gpustat (0.6.0). I am not comfortable merging into the 0.6.0 version of the conda package that has been released more than one year ago now.

Can you ask upstream to release a new version and we will just build a new package here once this is done? In the meantime, you should rely on a pip install from `master`.

pinging @conda-forge/help-python in case they have an opinion different than mine here.

**Comment by vnlitvinov** [comment]
I can technically revert most of Windows-specific patches, as they were relevant for _running_ the thing on Windows (and won't trigger in the CI).
However, as my main point was enabling this on Windows, I decided to add them 😃 

I sure will contact the upstream.

**Comment by vnlitvinov** [comment]
@hadim
Also do note that this PR adds running `gpustat` tests (which helped uncovering all the things), which adds to the amount of changed lines.

**Comment by hadim** [comment]
Agree with the tests and thanks for the work!

But my point is we should not change the deps of the version of the package neither add a patch of any sort nor it could break other person pipeline if they rely on this specific version.

I am fine merging the added tests, bumping the build number but without the patches and the switch to blessed. For this, I would wait for the upstream release.

**Comment by vnlitvinov** [comment]
@hadim extracted re-render and tests into #3

**Comment by vnlitvinov** [comment]
Rebased off new master, converted into draft for now - waiting for upstream response.

**Comment by hadim** [comment]
Thanks, @vnlitvinov for your time and being comprehensive!

**Comment by h-vetinari** [comment]
There's been a [tag](https://github.com/wookayin/gpustat/releases/tag/v1.0.0b1) of `1.0.0b1` and https://github.com/wookayin/gpustat/pull/78 shortly after. It's been more than half a year since then - I've [asked](https://github.com/wookayin/gpustat/issues/57#issuecomment-897711670) upstream about the plan.

BTW, saw this PR too late before opening #4, sorry.

**Comment by mattip** [comment]
gpustat 1.0.0 supports windows

**Pull request closed without merging**
